server:
  port: 8081

spring:
  cloud:
    gateway:
      routes:
        - id: user
          uri: http://fiap-ms-user/
          predicates:
            - Path=/user/**
        - id: wallet
          uri: http://fiap-ms-wallet/
          predicates:
            - Path=/wallet/**
